- name: Create Instance on EC2 using Ubuntu Precise as base image
  hosts: local
  connection: local
  user: root
  gather_facts: false

  vars:
      keypair: default
      instance_type: m1.large
      security_group: default
      image: ami-0145d268 # base image is ubuntu-precise-12.04-amd64-server-20130204 (ebs/paravirtual)
      $tags: '{"owner":"Search Team","application":"bulk-math","role":"front-end"}'
      count: 1

  tasks:
    - name: Launch instance
      #local_action: ec2 keypair=$keypair group=$security_group instance_type=$instance_type image=$image instance_tags=$tags count=$count wait=true
      local_action: ec2 keypair=$keypair group=$security_group instance_type=$instance_type image=$image instance_tags='{"owner":"Search Team","application":"bulk-math","role":"front-end"}' count=$count wait=true
      register: ec2 # register (save) the output for later use

      # here we add the public_ip var from the list of ec2.instances to a host group called "launched", ready for the next play
    - name: Add new instances to host group
      local_action: add_host hostname=${item.public_ip} groupname=launched
      with_items: ${ec2.instances}

    - name: Wait to let the instance come up all the way
      local_action: pause minutes=1


- name: Install Oracle's JDK version 6.x
  hosts: launched
  user: ubuntu
  sudo: yes
  gather_facts: true

  tasks:
    - name: Upgrade distro and update cache
      apt: upgrade=dist update_cache=yes

    - name: Copy OAB file (Used to create deb)
      copy: src=playbooks/files/oab-java.sh dest=/root/oab-java.sh mode=777

    - name: Extract JRE and build local repository
      # For Java 7.x
      #shell: cd /root && ./oab-java.sh -7
      shell: cd /root && ./oab-java.sh

    - name: Install JRE
      apt: pkg=sun-java6-jre state=installed 
      # For Java 7.x
      #apt: pkg=oracle-java7-jre state=installed 

      # need to set JAVA_HOME???
    - name: Install Tomcat 7
      apt: pkg=tomcat7 state=installed

  
